Minor: update the agent docker command after the onboarding support
superblocksteam/agent pull request #1
Opened 2021-12-20 03:50 UTC by ctan888

2021-12-20 15:25 UTC, taha-au requested changes

2021-12-20 15:25 UTC, taha-au commented on README.md
> +| SUPERBLOCKS_AGENT_HOST_URL                      | URL used by end-users to access the agent                                        | Yes      | n/a                           |
SUPERBLOCKS_AGENT_HOST_URL defaults to `http://localhost:8020/agent`

2021-12-20 15:28 UTC, taha-au requested changes

2021-12-20 15:28 UTC, taha-au commented on README.md
> +| SUPERBLOCKS_AGENT_HOST_URL                      | URL used by end-users to access the agent                                        | Yes      | n/a                           |
Change the description to the following
```
URL used by end-users to access the agent; should be overridden for non-localhost deployments
```

Change required to No

2021-12-20 15:38 UTC, taha-au commented
@ctan888 Also update the docker run and docker compose commands in the appropriate sections

2021-12-20 16:55 UTC, ctan888 commented
> @ctan888 Also update the docker run and docker compose commands in the Deployment section

I think I already have them updated. Let me know something specific is missing here.

2021-12-21 13:29 UTC, taha-au approved these changes

2021-12-21 13:30 UTC, merged