Introduce New Chart for the Agent Platform Architecture
superblocksteam/agent pull request #38
Opened 2022-05-19 16:53 UTC by frankgreco

```
---
# Source: superblocks-agent/templates/secret-key.yaml
apiVersion: v1
kind: Secret
metadata:
  name: superblocks
  namespace: default
  labels:
    helm.sh/chart: superblocks-agent-0.23.0
    app.kubernetes.io/name: superblocks-agent
    app.kubernetes.io/instance: superblocks
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  SUPERBLOCKS_AGENT_KEY: "bXktdGVzdC1rZXk="
---
# Source: superblocks-agent/templates/secret-tls.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: superblocks-agent-worker-tls
  labels:
    helm.sh/chart: superblocks-agent-0.23.0
    app.kubernetes.io/name: superblocks-agent
    app.kubernetes.io/instance: superblocks
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
  # We could use Helm hooks here but there's some weird behvaior.
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lSQU9KMkZDU3RWN3VQRWxHSG91RlYvazB3RFFZSktvWklodmNOQVFFTEJRQXcKRHpFTk1Bc0dBMVVFQXhNRWNtOXZkREFlRncweU1qQTFNVGt4TmpVeE5UaGFGdzB5TXpBMU1Ua3hOalV4TlRoYQpNQkV4RHpBTkJnTlZCQU1UQm1Oc2FXVnVkRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBTGM5cHZZWVlMUUk2eWxRSWswWWwwZjBxbFZ6aWZIbEpCc21Lam5mdkRYdTEzYVI2cURkWnFHZElqVGYKTW91b3hoQllWSEdkWFpZT0dxNzhjN1JmYnZUYkUvelltdldmRFZzN3R2VzhpSXEzSlVldkZuNXZSVjBGVGpRRQpUUGRCUWZhSnFidzJJN0ZieU5PZkkrSkNyditmZmVsTzVzMm9XYXkwWmZzSGk0VTJRVTI3RVVaOFR4SjdkTTNwClhMWmIreVNhdjdEa0RoVzJTSzNFcllQMEFZSGQwNW1EVjRoNExCQlRNR091c0VDeE0yNzF1RjkwTlMxU2Z6c1MKVzVENjdFanJlUlkxc0VHMmkxMFVWQnA4MFVSMEFNeklGKzlRMFNmcjZOS3RnVkFnNzk5anhRU254R1RGRGo1RgpzSXhaMS9jcVpaVzlGTEJSakhHWVhyeE5tUXNDQXdFQUFhTmdNRjR3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHCkExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUI4R0ExVWQKSXdRWU1CYUFGSVphVG9HME9KVm5yRHh1TDV5bTNaa0dtUHY5TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBUQpKckZVQ0h3Y2ZKRjBDZ09xald4Ny9qN3BCMWVNdllCYmRhL25NaVViL1hsaTVYZnBkT2kxd1FueFVCcmFpZTFLCkNjNng0QU1ERnd0K3htWXBxdnNxS1NKY01IdFFuallPQkpIRmYxZHlPN096UFVsSmUzUWxiNG5HTVlSamZaRnYKSmh1UzZ2MGgwMjdmM0dYZnJCamRTMnB5R2R3c2VRemJLYi9vQWFDSGJiWjVNVEYxUFhUQjFZdmhaQ04xN1lybwo2ckljWW9Bdk1McUUrUWNKZ21jMGRzaEtFdEtLenJXMW54QmdwNEFpUGN6ZVUwN0wxUUhGZVB3aTJjN3pEMHA3Cjh0RW5UbzJ1RGl1OU1pQVZkWEdDMmFoUHZDa2x4VkxvMnBmdmo4UUFIcXloNGVEcEZSRzVNci91WnZhQTZNY0QKRU5rdDdOVnR5ZUIzOGNwZnpsZ3kKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdHoybTloaGd0QWpyS1ZBaVRSaVhSL1NxVlhPSjhlVWtHeVlxT2QrOE5lN1hkcEhxCm9OMW1vWjBpTk44eWk2akdFRmhVY1oxZGxnNGFydnh6dEY5dTlOc1QvTmlhOVo4Tld6dTI5YnlJaXJjbFI2OFcKZm05RlhRVk9OQVJNOTBGQjlvbXB2RFlqc1Z2STA1OGo0a0t1LzU5OTZVN216YWhackxSbCt3ZUxoVFpCVGJzUgpSbnhQRW50MHplbGN0bHY3SkpxL3NPUU9GYlpJcmNTdGcvUUJnZDNUbVlOWGlIZ3NFRk13WTY2d1FMRXpidlc0ClgzUTFMVkovT3hKYmtQcnNTT3Q1RmpXd1FiYUxYUlJVR256UlJIUUF6TWdYNzFEUkordm8wcTJCVUNEdjMyUEYKQktmRVpNVU9Qa1d3akZuWDl5cGxsYjBVc0ZHTWNaaGV2RTJaQ3dJREFRQUJBb0lCQVFDMjdYeE5OMTdxdS9DUAphS2tsa0FRT1dHam5MNVdwZjVoQTVpUEhiTnpHZHE1d2R4RGxFTUdSVzMyM2pJNDRMLyt5ZDR1dGRHem1EU1NFClJnLzRKRUZ2ZlhtQnRIZFY5emR0T2JyWHJTUWVYdUYvbzRId0xJTHhid2Q0RkVjRm13Y1A2TFFpNldWT2ZKT0sKOTlicDNLbzVGRzZ0U0JCUGhONG85RnJPZE9USzBRTlpJbjIzNzhpZVY0UjFSL1d5UndvOUkxQnFTR25OMktNTApiZDZUd2Z6TzhKNTJ1b20vVVFGOTZPMlNGSjVLWVYrMkJndWloZW5vTDFndWEyb2dKM2dpNnI4bTVlQkZUb3M3Ci90bW5KTGsvNUtBU2Z1Nzc1Z0JXeWpmd0lwWUxJd0c5QzlSQVBBbC9udjY2MW5SR0s2RnJDWCtFeVpaQWltZCsKSkpSUEdZR3BBb0dCQU5LQnc2VitpVTdKbVpndWl2akU1Z2ZBeEtlNGNwMnR6dVdEbDFTZThDU2h5MXBpWWh4TwpLN0J5OVpWb2ZLM0EyUy8rVm8xVlIwWlBxODZHMlJUalpLZWNiRE04UDNPREE1c2I1aDFXNnRndThsWmNWVW92ClhNVTlDNjlEOGtqR291SnNRQWh0dUZqdEtqb21zMFpLcllxZ0ZoWERzNGJBdFd5NkdUSmZ6RVhkQW9HQkFON1gKWm9vYnE4emJkVWUrQkVMaTQrV0xwODVZN0hHbkwySjkwYk1taGJPYlFEU2tESFMrWWdBaTZSYjY4N2NlS1A1MgpFTVdqbyswSHdiSU1Dc0gyZVViUUNjelkyYm8yNjBBaFJrdU9sNkFrVXpkVmF4UHJpL2FNMGVLY3JiNkQzSStOCmY1a2ZmbGUwWUsrSDR1NE9NaFBCY1lPdFBIMzdrS2ExZXpveTAzQUhBb0dCQUlSS2JJdTZvOHZSd2lielNQN2gKcnJZOG5OblNmcVU5TDRMcFdkY2lNMFN5TVR2U0RGcEJmZzliajU2ZmxZc1VZT2xhYTBaU3k0SVNXNlJrOWxPOApPK3RoMEZXNmpSMm92a0ZpSFJGZktDTklEWi9jVXZWV0luVUowaWdKQ1dCWEJOSkt1VXNTdVFHWnVpbmxYRkRXCmFZMXU0YkkzMU1EZ3BxTjNxSklSeGl3NUFvR0FSbE8raGJtajU1d2ZFRXcwdGhNN0R6ZWE5dkZ6ZFk3bzBuR1kKMjZ3OXAraElSQlM5NVo0citaVUs4UGkwTDhkeDhwUzZTRldUcDN1Nk1vSEFaMlJzODk4MktKTUxhOHhuUkM3OApLMTVPRmZsQTFnYThLMlk4SHN4a2ROc3pyaHVaWVNpcjYxeFlHRC9SLzdPbjk2ODlPS1RsT1VSVUFnS0JyVXM3Ckg2dm90TU1DZ1lBcnEwRklCRVI3QnhnRytrQmh5RXh1clNQQTdnaDV4cVhjZk1yRHF3UGV1ZVhNcW9QMnIyNXUKY2w0MHh0K0hIUTQxSnFoMTJWVVFRRkFQdDAxZEdqem4rdGZzaFl5Z0lxTEVKaktyMTdOblBtTjhZTzNRS3ZDcgpEcHV5UHVZTitndWJQdS9lTDRiZWJIdEhNdjZNdXgxNXEzNWYrSE9QMmFGZGFvQUM5eXdYQmc9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  tls.ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lSQVBzeHpwTzVmZ0dFRnRhVDFVVlpETHN3RFFZSktvWklodmNOQVFFTEJRQXcKRHpFTk1Bc0dBMVVFQXhNRWNtOXZkREFlRncweU1qQTFNVGt4TmpVeE5UaGFGdzB5TXpBMU1Ua3hOalV4TlRoYQpNQTh4RFRBTEJnTlZCQU1UQkhKdmIzUXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRQzcyWFNTc2Q2a0prcGZjRXFKdkN5andoKzFNTy9vWFRMb3VFWkZncXl0ZnVxTkdiaWdvcWVuVlpCRkI5ZkcKbGVTSjd2YnRKNVRENGFZeHBVdkNPVHlldjJCTFFESnV1RFlITWJucUVvTjJKbzZsN1FHRUpCZzR0bkd0R016RgpWY0hoTlFjazM4NUlCQVk1a0FMUHNnditZazJzUXIydmw1TytaajFXUWIrNlVXcWgxMExqNEJSditQcnBlcHlkCnFYKzk0L3FUbHlpeXNMaXFCZ1ZXMXVPeVR0N3RUYldKR3lXOTFrbyt5RC83Y1RsYkZDSHJaUzdRY1k0QjNmS0EKa3BBZC85dHFLVjlmd1hFcVhLVHhJR2RDQTJhUUhyREVON09wTjdRbmtRL1JkTzZjVnJnOUxWZGlHY3JiQnByLwpybHNXT0xhelg2M0Z3RWlSZ0l0WHdsaHJBZ01CQUFHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ3BEQWRCZ05WCkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVobHBPZ2JRNGxXZXNQRzR2bktiZG1RYVkrLzB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUxleQovczZLRDkyUWlWeHVkbVVHbWFwcWdrMGJRRGlUYk9JMmV2Z0NFM21VL2VBSFV5Z3hxb1U1ZzY2d3FFUGhuM3dVCjE0bmJPNDZjdWhPc0lGNHFZWktkcGxLOEMwNkJBRWdwcmFCbXYxQ0haSWkzYlJRS2t0QlVCaGdGeWlCMHdXdkoKamxsMHRPUXdGR04xRWIyTVBRb0EzNWR3S3I1YlBnYmV0d3hjbHNicTZ0RytoRDhCL1pBMUF1azBtYkFYTFVsdQpNbEJIWDBWQnp0N3FBaHBuTStwWXZoc05IZjh5NVQ5Rld6d0taOE1NQXJnYm8zbjVkZTExeGJwd3c3VVBwM2RYCk45OUJVWkt5U05qYyt2akxkSm4vWmtRaE9Cb1MrTzJSUXZMOGh1dzJJaTlhbjJwems2TXlGRVRERkZ4MVIrMjAKTEpwOTMzcnErRlVJK0xjYS9Sdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
---
# Source: superblocks-agent/templates/service-controller.yaml
apiVersion: v1
kind: Service
metadata:
  name: superblocks
  labels:
    helm.sh/chart: superblocks-agent-0.23.0
    app.kubernetes.io/name: superblocks-agent
    app.kubernetes.io/instance: superblocks
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 8020
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: superblocks-agent
    app.kubernetes.io/instance: superblocks
---
# Source: superblocks-agent/templates/deployment-controller.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: superblocks-agent-controller
  labels:
    helm.sh/chart: superblocks-agent-0.23.0
    app.kubernetes.io/name: superblocks-agent
    app.kubernetes.io/instance: superblocks
    app.kubernetes.io/version: "v0.36.0"
    app.kubernetes.io/managed-by: Helm
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: superblocks-agent
      app.kubernetes.io/instance: superblocks
      component: controller
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: superblocks-agent
        app.kubernetes.io/instance: superblocks
        component: controller
    spec:
      terminationGracePeriodSeconds: 86400
      securityContext:
        {}
      containers:
      - name: superblocks-agent-controller
        securityContext:
            {}
        image: "ghcr.io/superblocksteam/agent/controller:v0.36.0"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8020
          protocol: TCP
        - name: worker
          containerPort: 5001
          protocol: TCP
        livene [...]

2022-05-25 14:33 UTC, bruce-y commented on helm/templates/pdb-controller.yaml
> +{{- if .Values.controller.podDisruptionBudget -}}
Should we also include a worker pdb?

2022-05-27 21:59 UTC, frankgreco commented on helm/templates/hpa-controller.yaml
> +{{- if .Values.controller.autoscaling.enabled }}
I guess it doesn't hurt to have the based cpu/memory hpas and then optimize the metrics later.

2022-05-31 14:08 UTC, bruce-y approved these changes

2022-06-28 16:14 UTC, taha-au requested changes
LGTM other than the requested changes

2022-06-28 16:14 UTC, taha-au commented on docker/compose.yaml
> +    image: ${SUPERBLOCKS_DOCKER_CONTROLLER_REPOSITORY:-ghcr.io/superblocksteam/agent/controller}:${SUPERBLOCKS_DOCKER_CONTROLLER_TAG:-latest}
```suggestion
    image: ${SUPERBLOCKS_DOCKER_CONTROLLER_REPOSITORY:-ghcr.io/superblocksteam/agent-controller}:${SUPERBLOCKS_DOCKER_CONTROLLER_TAG:-latest}
```

2022-06-28 16:25 UTC, taha-au approved these changes
Pushed commit to address requested changes

2022-06-28 16:25 UTC, merged